version: "3.7"
services:
  etos-keys:
    build:
      context: .
      dockerfile: ./deploy/etos-keys/Dockerfile.dev
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    env_file:
      - ./configs/development.env
    entrypoint: ["/bin/bash", "./scripts/entrypoint.sh"]
