apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: etos-api
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/component: sse
  name: etos-sse
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etos-api
      app.kubernetes.io/component: sse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etos-api
        app.kubernetes.io/component: sse
    spec:
      serviceAccountName: etos-sse
      containers:
        - name: etos-sse
          image: ghcr.io/eiffel-community/etos-sse:d08fc6ac
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_HOST
              value: 0.0.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /sse/v1alpha/selftest/ping
              port: http
          readinessProbe:
            httpGet:
              path: /sse/v1alpha/selftest/ping
              port: http
